Pet/force-app/main/default/objects/Cliente__c/Cliente__c.object-meta.xml
<CustomObject>
    <label>Cliente</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Numero do Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Pet/force-app/main/default/objects/Cliente__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email de contato</description>
    <inlineHelpText>Email de contato</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ClientesHandler.cls
public without sharing class ClientesHandler {

    public void ClientesHandler{

    }

    public void enviarEmailAniversariantes(){
            enviarEmail(listaEmailsAniversariantes(ClienteSelector.obterEmailsAniversariantes()));
    }

    private void enviarEmail(List<String> emails){
        System.debug('Entrou no enviarEmailMassa');
        if(!emails.isEmpty()){
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(emails);
            email.setSubject('Aniversariante');
            email.setHtmlBody('Feliz aniversário');
            Messaging.sendEmail(email);
        }else{
            System.debug('Nenhum aniversariante encontrado no dia de hoje:' + System.today());  
        }
    }

    private List<String> listaEmailsAniversariantes(List<Cliente__c> listaClientesAniversariantes){
        List<String> emails;
        if(!listaClientesAniversariantes.isEmpty()){
            for(Cliente__c cliente : listaClientesAniversariantes){
                emails.add(cliente.Email__c);
            }
        }
        return emails;
    }

}